# Generated by Django 5.2.6 on 2025-09-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=100)),
                ('adverse_events_list', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('outcome', models.CharField(max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
